[package]
name = "cjson-rs"
version = "0.5.0"
authors = ["Antonio Salsi <passy.linux@zresa.it>"]
edition = "2024"
license = "GPL3"
readme = "README.md"
repository = "https://github.com/passy1977/cjson-rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"